(setq yeoman-backbone-jump-schema
      '(
        ("spec-c"      . "/\\1Controller.spec.js")
        ("spec-v"      . "/\\1View.spec.js")
        ("spec"        . "/\\1.spec.js")
        ("collection"  . "app/scripts/collections/\\1.js")
        ("controller"  . "app/scripts/controllers/\\1Controller.js")
        ("error"       . "app/scripts/errors/\\1.js")
        ("helper"      . "app/scripts/helpers/\\1.js")
        ("mixin"       . "app/scripts/mixins/\\1.js")
        ("model"       . "app/scripts/models/\\1.js")
        ("renderer"    . "app/scripts/renderers/\\1Renderer.js")
        ("route"       . "app/scripts/routes/\\1.js")
        ("service"     . "app/scripts/services/\\1.js")
        ("template"    . "app/scripts/templates/\\1.js")
        ("translation" . "app/scripts/translations/\\1.js")
        ("assembler"   . "app/scripts/views/components/assemblers/\\1Control.js")
        ("widget"      . "app/scripts/views/components/widgets/\\1Control.js")
        ("component"   . "app/scripts/views/components/\\1.js")
        ("view"        . "app/scripts/views/\\1View.js")
        ("sass"        . "app/styles/sass/\\1.scss")
        ))

(add-hook 'js2-mode-hook
          (lambda ()
            (yeoman-backbone)))

(define-key yeoman-backbone-keymap (kbd "C-c f o") #'yeoman-bb-open-collection)
(define-key yeoman-backbone-keymap (kbd "C-c f c") #'yeoman-bb-open-controller)
(define-key yeoman-backbone-keymap (kbd "C-c f e") #'yeoman-bb-open-error)
(define-key yeoman-backbone-keymap (kbd "C-c f h") #'yeoman-bb-open-helper)
(define-key yeoman-backbone-keymap (kbd "C-c f x") #'yeoman-bb-open-mixin)
(define-key yeoman-backbone-keymap (kbd "C-c f m") #'yeoman-bb-open-model)
(define-key yeoman-backbone-keymap (kbd "C-c f n") #'yeoman-bb-open-renderer)
(define-key yeoman-backbone-keymap (kbd "C-c f r") #'yeoman-bb-open-route)
(define-key yeoman-backbone-keymap (kbd "C-c f S") #'yeoman-bb-open-service)
(define-key yeoman-backbone-keymap (kbd "C-c f t") #'yeoman-bb-open-template)
(define-key yeoman-backbone-keymap (kbd "C-c f i") #'yeoman-bb-open-translation)
(define-key yeoman-backbone-keymap (kbd "C-c f v") #'yeoman-bb-open-view)
(define-key yeoman-backbone-keymap (kbd "C-c f p") #'yeoman-bb-open-component)
(define-key yeoman-backbone-keymap (kbd "C-c f w") #'yeoman-bb-open-widget)
(define-key yeoman-backbone-keymap (kbd "C-c f a") #'yeoman-bb-open-assembler)
(define-key yeoman-backbone-keymap (kbd "C-c f s") #'yeoman-bb-open-sass)
(define-key yeoman-backbone-keymap (kbd "C-c f k") #'yeoman-bb-open-spec-or-target)
